/**
 * Image cache for the current user turn.
 *
 * Tracks image URLs generated by blu-generate-image during one user turn so
 * downstream handlers (handleEditBlock, handleAddSection) can deduplicate
 * repeated URLs in AI-emitted markup and substitute unused images.
 */

/**
 * Module-level tracker for image URLs generated during this user turn.
 * Populated by blu-generate-image results, consumed by handleAddSection
 * and handleEditBlock for deduplication.
 */
let generatedImageUrls = [];

/**
 * Get the current list of generated image URLs (live reference, do not mutate
 * externally — use appendGeneratedImageUrl / resetGeneratedImageCache).
 *
 * @return {string[]} The array of URLs collected so far this turn.
 */
export function getGeneratedImageUrls() {
	return generatedImageUrls;
}

/**
 * Append a newly generated image URL to the turn's cache.
 *
 * @param {string} url Image URL returned by blu-generate-image.
 */
export function appendGeneratedImageUrl(url) {
	generatedImageUrls.push(url);
}

/**
 * Clear the generated image tracker.
 * Called at the start of each new user turn so stale results from a
 * previous request don't contaminate the next request.
 */
export function resetGeneratedImageCache() {
	generatedImageUrls = [];
}

/**
 * Extract all image URLs from block markup (src attributes of img tags).
 *
 * @param {string} markup Block markup
 * @return {string[]} Array of image URLs found in the markup
 */
export function extractImageUrls(markup) {
	const urls = [];
	const re = /<img\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi;
	let m;
	while ((m = re.exec(markup)) !== null) {
		urls.push(m[1]);
	}
	return urls;
}

/**
 * Replace duplicate image URLs in block markup with unused generated images.
 *
 * Scans `markup` for <img> src values that appear more than once.  For each
 * duplicate occurrence (after the first), substitutes an unused URL from
 * `availableUrls`.  Returns the patched markup and a list of replacements
 * made (for logging).
 *
 * @param {string}   markup        Block markup HTML string
 * @param {string[]} availableUrls Pool of generated image URLs to draw from
 * @return {{ markup: string, replacements: Array<{from: string, to: string}> }} The deduplicated markup and list of replacements made.
 */
export function deduplicateImages(markup, availableUrls) {
	const imgUrls = extractImageUrls(markup);
	if (imgUrls.length === 0) {
		return { markup, replacements: [] };
	}

	// Find URLs that appear more than once
	const seen = new Map(); // url → count
	for (const url of imgUrls) {
		seen.set(url, (seen.get(url) || 0) + 1);
	}

	const duplicateUrls = [...seen.entries()].filter(([, count]) => count > 1).map(([url]) => url);

	if (duplicateUrls.length === 0) {
		return { markup, replacements: [] };
	}

	// Build pool of unused URLs (generated but not referenced in markup)
	const usedInMarkup = new Set(imgUrls);
	const unusedPool = availableUrls.filter((u) => !usedInMarkup.has(u));

	const replacements = [];
	let result = markup;

	for (const dupUrl of duplicateUrls) {
		// Find all occurrences — keep the first, replace subsequent
		const escaped = dupUrl.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
		const srcRe = new RegExp(`(src=["'])${escaped}(["'])`, "g");
		let matchIdx = 0;
		result = result.replace(srcRe, (full, pre, post) => {
			matchIdx++;
			if (matchIdx === 1) {
				return full;
			} // keep first occurrence
			if (unusedPool.length > 0) {
				const replacement = unusedPool.shift();
				replacements.push({ from: dupUrl, to: replacement });
				return `${pre}${replacement}${post}`;
			}
			return full; // no unused images available
		});
	}

	return { markup: result, replacements };
}
