import { setAltForImageSrc } from "../utils/imageAlt";

/**
 * Image cache for the current user turn.
 *
 * Tracks image URLs generated by blu-generate-image during one user turn so
 * downstream handlers (handleEditBlock, handleAddSection) can deduplicate
 * repeated URLs in AI-emitted markup and substitute unused images.
 */

/**
 * Module-level tracker for image URLs generated during this user turn.
 * Populated by blu-generate-image results, consumed by handleAddSection
 * and handleEditBlock for deduplication.
 */
let generatedImages = [];

/**
 * clientId of the image block the user is currently editing, captured when an
 * image-edit request is sent (the chat sidebar steals selection from the
 * canvas, so getSelectedBlock() is unreliable at tool-dispatch time). Lets the
 * dispatcher route blu-generate-image → blu-edit-image and apply the result to
 * the block. The block itself is resolved at dispatch time (it still exists,
 * just isn't "selected").
 *
 * @type {string|null}
 */
let activeImageEditClientId = null;

/**
 * Record the image block targeted by the current edit request.
 *
 * @param {string|null} clientId
 */
export function setActiveImageEditTarget(clientId) {
	activeImageEditClientId = clientId || null;
}

/**
 * Get the clientId of the image block targeted by the current edit request.
 *
 * @return {string|null} The clientId of the image block targeted by the current edit request.
 */
export function getActiveImageEditTarget() {
	return activeImageEditClientId;
}

/**
 * Get the images generated this turn, each with the alt text that describes it.
 *
 * @return {Array<{url: string, alt: string}>} Entries collected so far this turn.
 */
export function getGeneratedImages() {
	return generatedImages;
}

/**
 * Append a newly generated image to the turn's cache.
 *
 * @param {string} url   Image URL returned by blu-generate-image.
 * @param {string} [alt] Alt text describing it (model-supplied or prompt-derived).
 */
export function appendGeneratedImageUrl(url, alt = "") {
	generatedImages.push({ url, alt: alt || "" });
}

/**
 * Clear the generated image tracker.
 * Called at the start of each new user turn so stale results from a
 * previous request don't contaminate the next request.
 */
export function resetGeneratedImageCache() {
	generatedImages = [];
	activeImageEditClientId = null;
}

/**
 * Substitute a __IMG_N__ placeholder with a real image, alt text included.
 *
 * The placeholder only stands in for the URL, so the model's surrounding
 * `alt` was written before the image existed (its own examples use alt="").
 * Applying alt here keeps the description tied to the picture actually used.
 *
 * @param {string} markup Block markup containing placeholders
 * @param {number} index  1-based placeholder number (__IMG_1__ is index 1)
 * @param {string} url    Resolved image URL
 * @param {string} [alt]  Alt text describing the image
 * @return {string} Markup with that placeholder resolved
 */
export function substituteImagePlaceholder(markup, index, url, alt = "") {
	if (!markup || !url) {
		return markup;
	}
	const resolved = markup.replaceAll(`__IMG_${index}__`, url);
	return alt ? setAltForImageSrc(resolved, url, alt) : resolved;
}

/**
 * Build a tool error for markup whose image placeholders never resolved.
 *
 * Writing the placeholder through renders a broken <img>, and calling that a
 * success sends the model into a repair loop it cannot win.
 *
 * @param {string} toolCallId The tool call id to answer.
 * @param {string} markup     Block markup after the image step.
 * @return {Object|null} An error result, or null when nothing is unresolved.
 */
export function unresolvedPlaceholderResult(toolCallId, markup) {
	const leftover = markup?.match(/__IMG_\d+__/g);
	if (!leftover || leftover.length === 0) {
		return null;
	}
	const unique = [...new Set(leftover)];
	return {
		id: toolCallId,
		result: [
			{
				type: "text",
				text: JSON.stringify({
					success: false,
					error:
						`Image generation is unavailable, so ${unique.join(", ")} could not be resolved. ` +
						`Nothing was changed. Tell the user that image generation failed: do not retry ` +
						`this edit and do not write the placeholder into the page.`,
				}),
			},
		],
		isError: true,
	};
}

/**
 * Extract all image URLs from block markup (src attributes of img tags).
 *
 * @param {string} markup Block markup
 * @return {string[]} Array of image URLs found in the markup
 */
export function extractImageUrls(markup) {
	const urls = [];
	const re = /<img\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi;
	let m;
	while ((m = re.exec(markup)) !== null) {
		urls.push(m[1]);
	}
	return urls;
}

/**
 * Replace duplicate image URLs in block markup with unused generated images.
 *
 * Scans `markup` for <img> src values that appear more than once. For each
 * duplicate occurrence (after the first), substitutes an unused image from
 * `availableImages`. The substituted tag's alt is rewritten too — the tag now
 * shows a different picture, so the original alt would describe something that
 * is no longer there.
 *
 * @param {string}                            markup          Block markup HTML string
 * @param {Array<{url: string, alt: string}>} availableImages Pool of generated images to draw from
 * @return {{ markup: string, replacements: Array<{from: string, to: string}> }} The deduplicated markup and list of replacements made.
 */
export function deduplicateImages(markup, availableImages) {
	const imgUrls = extractImageUrls(markup);
	if (imgUrls.length === 0) {
		return { markup, replacements: [] };
	}

	// Find URLs that appear more than once
	const counts = new Map(); // url → count
	for (const url of imgUrls) {
		counts.set(url, (counts.get(url) || 0) + 1);
	}
	const duplicated = new Set(
		[...counts.entries()].filter(([, count]) => count > 1).map(([url]) => url)
	);
	if (duplicated.size === 0) {
		return { markup, replacements: [] };
	}

	// Pool of images generated this turn but not already referenced in markup
	const usedInMarkup = new Set(imgUrls);
	const unusedPool = availableImages.filter((image) => !usedInMarkup.has(image.url));

	const replacements = [];
	const keptFirst = new Set();

	// Rewrite whole <img> tags rather than the src attribute alone, so alt can
	// be updated on the same tag.
	const result = markup.replace(/<img\b[^>]*>/gi, (tag) => {
		const src = tag.match(/src=["']([^"']+)["']/i)?.[1];
		if (!src || !duplicated.has(src)) {
			return tag;
		}
		if (!keptFirst.has(src)) {
			keptFirst.add(src);
			return tag;
		}
		if (unusedPool.length === 0) {
			return tag;
		}
		const image = unusedPool.shift();
		replacements.push({ from: src, to: image.url });
		const swapped = tag.replace(/src=["'][^"']+["']/i, `src="${image.url}"`);
		return setAltForImageSrc(swapped, image.url, image.alt);
	});

	return { markup: result, replacements };
}
